variables:
  serviceConnectionToAzure: AzureDevOps
  appName: businesstest1

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
  displayName: 'npm install'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    WebAppName: $(appName)
    Package: '$(System.DefaultWorkingDirectory)'
    GenerateWebConfig: true
    WebConfigParameters: '-Handler iisnode -NodeStartFile server/index.js -appType node'
