# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  serviceConnectionToAzure: AzureDevOps
  appName: businesstest1

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- script: |
    npm install
  displayName: 'npm install'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    WebAppName: $(appName)
    Package: '$(System.DefaultWorkingDirectory)'
    GenerateWebConfig: true
    WebConfigParameters: '-Handler iisnode -NodeStartFile server.js -appType node'
